import { MedicationPicker } from "@/app/MedicationPicker";
import { MedicationSchedulePicker } from "@/app/MedicationSchedulePicker";
import { addMedication, completeMonitoringTask, deleteMedication, toggleMedicationTaken } from "@/app/actions";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import rules from "@/app/monitoring_rules.json";
import { dateKey, medicationTasksForDate, monitoringTasksForDate } from "@/app/tasks";
import { getDb } from "@/db";
import { medicationLogs, medications, monitoringCompletions } from "@/db/schema";
import { and, desc, eq, gte, lt } from "drizzle-orm";

export const dynamic = "force-dynamic";

const C = { text: "#1A2050", muted: "rgba(26,32,80,0.42)", card: "rgba(255,255,255,0.72)", border: "rgba(255,255,255,0.9)" };
const input = { width: "100%", padding: "11px 12px", background: "rgba(244,246,255,0.8)", border: "1px solid rgba(186,200,255,0.4)", borderRadius: 11, fontSize: 16, color: "#1A2050" } as const;

export default async function MedicationsPage() {
  const user = await getChatGPTUser();
  if (!user) return <div style={{ padding: 24, color: C.text }}>Войдите через ChatGPT, чтобы открыть лекарства.</div>;
  const db = getDb();
  const rows = await db.select().from(medications).where(and(eq(medications.userId, user.userId), eq(medications.isActive, true))).orderBy(desc(medications.createdAt));
  const today = new Date();
  const key = dateKey(today);
  const logs = await db.select().from(medicationLogs).where(and(eq(medicationLogs.userId, user.userId), gte(medicationLogs.scheduledAt, `${key}T00:00:00`), lt(medicationLogs.scheduledAt, `${key}T23:59:59`)));
  const completions = await db.select().from(monitoringCompletions).where(eq(monitoringCompletions.userId, user.userId));
  const tasks = medicationTasksForDate(rows, logs, today);
  const monitoring = monitoringTasksForDate(rows, completions, rules, today);
  const taken = tasks.filter((task) => task.taken).length;
  const todayLabel = today.toLocaleDateString("ru-RU", { day: "numeric", month: "long" });
  return <div style={{ padding: "12px 16px 0", color: C.text }}>
    <div style={{ fontSize: 24, fontWeight: 700, paddingTop: 12 }}>Лекарства</div>
    <div style={{ fontSize: 12, color: C.muted, marginBottom: 20 }}>Задачи на сегодня · {todayLabel}</div>
    <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 20, padding: "15px 17px", marginBottom: 18 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, fontWeight: 700, marginBottom: 10 }}><span>Приём сегодня</span><span style={{ color: "#5C7CFA" }}>{taken} / {tasks.length}</span></div><div style={{ height: 6, background: "rgba(26,32,80,0.07)", borderRadius: 4 }}><div style={{ height: "100%", width: tasks.length ? `${Math.round((taken / tasks.length) * 100)}%` : "0%", background: "linear-gradient(90deg,#748FFC,#74C0FC)", borderRadius: 4 }} /></div><div style={{ fontSize: 11, color: C.muted, marginTop: 8 }}>{tasks.length ? (taken === tasks.length ? "Все задачи на сегодня выполнены 🎉" : "Отмечайте каждый отдельный приём") : "Нет запланированных приёмов на сегодня"}</div></div>
    <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 10 }}>Сегодня</div>
    {tasks.length === 0 ? <div style={{ color: C.muted, fontSize: 13, padding: "10px 0 16px" }}>{rows.length ? "Есть лекарства без задач по времени или они принимаются по необходимости." : "Пока нет лекарств. Добавьте препарат ниже."}</div> : tasks.map((task) => <div key={task.key} style={{ display: "flex", alignItems: "center", gap: 10, padding: "11px 13px", marginBottom: 6, background: C.card, border: `1px solid ${C.border}`, borderRadius: 14, opacity: task.taken ? 0.62 : 1 }}><form action={toggleMedicationTaken}><input type="hidden" name="medicationId" value={task.medicationId} /><input type="hidden" name="scheduledAt" value={task.scheduledAt} /><button type="submit" aria-label={task.taken ? "Отменить приём" : "Отметить приём"} style={{ width: 29, height: 29, borderRadius: "50%", border: task.taken ? 0 : "1.5px solid rgba(26,32,80,0.18)", background: task.taken ? "linear-gradient(135deg,#748FFC,#74C0FC)" : "transparent", color: "white", fontSize: 14 }}>{task.taken ? "✓" : ""}</button></form><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 600, textDecoration: task.taken ? "line-through" : "none" }}>{task.name}</div><div style={{ fontSize: 11, color: C.muted }}>{task.time}{task.dosage ? ` · ${task.dosage}` : ""}</div></div></div>)}
    {monitoring.length > 0 && <><div style={{ fontSize: 13, fontWeight: 700, margin: "18px 0 10px" }}>Напоминания курса</div>{monitoring.map((item) => <div key={`${item.id}:${item.medicationId}`} style={{ background: C.card, border: `1px solid ${item.overdue ? "rgba(224,49,49,0.26)" : C.border}`, borderRadius: 14, padding: "12px 13px", marginBottom: 7 }}><div style={{ display: "flex", gap: 9, alignItems: "flex-start" }}><div style={{ fontSize: 18 }}>🧪</div><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 700 }}>{item.title_ru}</div><div style={{ fontSize: 11, color: C.muted, marginTop: 3 }}>{item.reason_ru} · {item.medicationName}</div><div style={{ fontSize: 11, color: item.overdue ? "#E03131" : "#D97706", marginTop: 5 }}>{item.overdue ? "Просрочено" : "Запланировано"}: {item.dueDate}</div></div></div><details style={{ marginTop: 8 }}><summary style={{ cursor: "pointer", color: "#5C7CFA", fontSize: 12 }}>Что проверить</summary><div style={{ fontSize: 11, color: C.muted, lineHeight: 1.5, marginTop: 7 }}>{item.tests_ru.join(" · ")}<br />{item.schedule_ru}</div><form action={completeMonitoringTask} style={{ marginTop: 9 }}><input type="hidden" name="medicationId" value={item.medicationId} /><input type="hidden" name="ruleId" value={item.id} /><input type="hidden" name="repeatDays" value={item.repeat_days} /><button type="submit" style={{ padding: "8px 10px", border: 0, borderRadius: 9, background: "rgba(92,124,250,0.1)", color: "#5C7CFA", fontWeight: 700, fontSize: 12 }}>Отметить выполненным</button></form></details></div>)}</>}
    <details style={{ marginTop: 18, background: C.card, border: `1px solid ${C.border}`, borderRadius: 16, padding: "13px 14px" }}><summary style={{ cursor: "pointer", fontSize: 13, fontWeight: 700 }}>Мои препараты · {rows.length}</summary><div style={{ marginTop: 12, display: "grid", gap: 8 }}>{rows.map((med) => <div key={med.id} style={{ padding: "11px 12px", background: "rgba(244,246,255,0.65)", borderRadius: 13 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><div><div style={{ fontSize: 13, fontWeight: 700 }}>{med.name}</div><div style={{ fontSize: 11, color: C.muted }}>{med.frequency === "as_needed" ? "По необходимости" : med.frequency === "weekly" ? "Несколько раз в неделю" : "Каждый день"}{med.dosage ? ` · ${med.dosage}` : ""}</div></div><span style={{ color: "#20C997", fontSize: 11 }}>активно</span></div><details style={{ marginTop: 8 }}><summary style={{ cursor: "pointer", color: "#5C7CFA", fontSize: 12 }}>Изменить или удалить</summary><form action={addMedication} style={{ display: "grid", gap: 8, marginTop: 10 }}><input type="hidden" name="id" value={med.id} /><MedicationPicker initialName={med.name} initialCode={med.drugCode || ""} /><input name="dosage" defaultValue={med.dosage || ""} placeholder="Дозировка" style={input} /><MedicationSchedulePicker initialFrequency={med.frequency || "daily"} initialSchedule={med.timeSlots || ""} /><div style={{ display: "flex", gap: 8 }}><input name="startDate" defaultValue={med.startDate || ""} type="date" style={{ ...input, flex: 1 }} /><input name="endDate" defaultValue={med.endDate || ""} type="date" style={{ ...input, flex: 1 }} /></div><button type="submit" style={{ padding: 10, border: 0, borderRadius: 10, background: "#5C7CFA", color: "white", fontWeight: 700 }}>Сохранить изменения</button></form><form action={deleteMedication} style={{ marginTop: 7 }}><input type="hidden" name="id" value={med.id} /><button type="submit" style={{ padding: 9, border: 0, background: "transparent", color: "#E03131", fontWeight: 600 }}>Удалить лекарство</button></form></details></div>)}</div></details>
    <details open={rows.length === 0} style={{ marginTop: 10, background: C.card, border: `1px solid ${C.border}`, borderRadius: 16, padding: "13px 14px" }}><summary style={{ cursor: "pointer", fontSize: 13, fontWeight: 700 }}>+ Добавить лекарство</summary><form action={addMedication} style={{ display: "grid", gap: 9, marginTop: 13 }}><MedicationPicker /><input name="dosage" placeholder="Дозировка" style={input} /><MedicationSchedulePicker /><div style={{ display: "flex", gap: 8 }}><input name="startDate" type="date" style={{ ...input, flex: 1 }} /><input name="endDate" type="date" style={{ ...input, flex: 1 }} /></div><select name="mealRelation" defaultValue="any" style={input}><option value="any">Неважно</option><option value="before">До еды</option><option value="during">Во время еды</option><option value="after">После еды</option></select><button type="submit" style={{ padding: 12, border: 0, borderRadius: 12, background: "linear-gradient(135deg,#748FFC,#5C7CFA)", color: "white", fontWeight: 700 }}>Сохранить лекарство</button></form></details>
  </div>;
}
