import { MedicationPicker } from "@/app/MedicationPicker";
import { addMedication, deleteMedication, toggleMedicationTaken } from "@/app/actions";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { getDb } from "@/db";
import { medicationLogs, medications } from "@/db/schema";
import { and, eq, gte, lt } from "drizzle-orm";

export const dynamic = "force-dynamic";

const C = { text: "#1A2050", muted: "rgba(26,32,80,0.42)", card: "rgba(255,255,255,0.72)", border: "rgba(255,255,255,0.9)" };
const input = { width: "100%", padding: "11px 12px", background: "rgba(244,246,255,0.8)", border: "1px solid rgba(186,200,255,0.4)", borderRadius: 11, fontSize: 16, color: "#1A2050" } as const;

export default async function MedicationsPage() {
  const user = await getChatGPTUser();
  if (!user) return <div style={{ padding: 24, color: C.text }}>Войдите через ChatGPT, чтобы открыть лекарства.</div>;
  const db = getDb();
  const rows = await db.select().from(medications).where(and(eq(medications.userId, user.userId), eq(medications.isActive, true)));
  const today = new Date().toISOString().slice(0, 10);
  const logs = await db.select().from(medicationLogs).where(and(eq(medicationLogs.userId, user.userId), gte(medicationLogs.scheduledAt, `${today}T00:00:00`), lt(medicationLogs.scheduledAt, `${today}T23:59:59`)));
  const taken = new Set(logs.filter((log) => log.status === "taken").map((log) => log.medicationId));
  return <div style={{ padding: "12px 16px 0", color: C.text }}>
    <div style={{ fontSize: 24, fontWeight: 700, paddingTop: 12 }}>Лекарства</div><div style={{ fontSize: 12, color: C.muted, marginBottom: 20 }}>Ваш список и приём на сегодня</div>
    <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 20, padding: "15px 17px", marginBottom: 20 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, fontWeight: 700, marginBottom: 10 }}><span>Прогресс дня</span><span style={{ color: "#5C7CFA" }}>{taken.size} / {rows.length}</span></div><div style={{ height: 4, background: "rgba(26,32,80,0.07)", borderRadius: 2 }}><div style={{ height: "100%", width: rows.length ? `${Math.round((taken.size / rows.length) * 100)}%` : "0%", background: "linear-gradient(90deg,#748FFC,#74C0FC)", borderRadius: 2 }} /></div></div>
    {rows.length === 0 ? <div style={{ color: C.muted, fontSize: 13, padding: "14px 0" }}>Пока нет лекарств. Введите название — появятся подсказки из справочника.</div> : rows.map((med) => { const time = (() => { try { return JSON.parse(med.timeSlots || "[]")[0] || "12:00"; } catch { return "12:00"; } })(); return <div key={med.id} style={{ padding: "12px 13px", marginBottom: 7, background: C.card, border: `1px solid ${C.border}`, borderRadius: 14 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ width: 8, height: 8, borderRadius: "50%", background: taken.has(med.id) ? "#20C997" : "#D0BFFF" }} /><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 600 }}>{med.name}</div><div style={{ fontSize: 11, color: C.muted }}>{[med.dosage, med.frequency, time, med.mealRelation].filter(Boolean).join(" · ")}</div></div><form action={toggleMedicationTaken}><input type="hidden" name="medicationId" value={med.id} /><input type="hidden" name="time" value={time} /><button type="submit" aria-label={taken.has(med.id) ? "Отменить приём" : "Отметить приём"} style={{ width: 28, height: 28, borderRadius: "50%", border: taken.has(med.id) ? 0 : "1.5px solid rgba(26,32,80,0.18)", background: taken.has(med.id) ? "linear-gradient(135deg,#748FFC,#74C0FC)" : "transparent", color: "white", fontSize: 13 }}>{taken.has(med.id) ? "✓" : ""}</button></form></div><details style={{ marginTop: 8 }}><summary style={{ fontSize: 11, color: "#5C7CFA", cursor: "pointer" }}>Изменить или удалить</summary><form action={addMedication} style={{ display: "grid", gap: 8, marginTop: 10 }}><input type="hidden" name="id" value={med.id} /><MedicationPicker initialName={med.name} initialCode={med.drugCode || ""} /><input name="dosage" defaultValue={med.dosage || ""} placeholder="Дозировка" style={input} /><input name="frequency" defaultValue={med.frequency || ""} placeholder="Как часто" style={input} /><input name="time" defaultValue={time} type="time" style={input} /><select name="mealRelation" defaultValue={med.mealRelation || ""} style={input}><option value="">Связь с едой не указана</option><option value="before">До еды</option><option value="during">С едой</option><option value="after">После еды</option></select><button type="submit" style={{ padding: 10, border: 0, borderRadius: 10, background: "#5C7CFA", color: "white", fontWeight: 700 }}>Сохранить изменения</button></form><form action={deleteMedication} style={{ marginTop: 7 }}><input type="hidden" name="id" value={med.id} /><button type="submit" style={{ padding: 9, border: 0, background: "transparent", color: "#E03131", fontWeight: 600 }}>Удалить лекарство</button></form></details></div>; })}
    <details style={{ marginTop: 18, background: C.card, border: `1px solid ${C.border}`, borderRadius: 16, padding: "13px 14px" }}><summary style={{ cursor: "pointer", fontSize: 13, fontWeight: 700 }}>+ Добавить лекарство</summary><form action={addMedication} style={{ display: "grid", gap: 9, marginTop: 13 }}><MedicationPicker /><input name="dosage" placeholder="Дозировка, например 10 мг" style={input} /><input name="frequency" placeholder="Как часто, например каждый день" style={input} /><input name="time" type="time" style={input} defaultValue="08:00" /><select name="mealRelation" style={input} defaultValue=""><option value="">Связь с едой не указана</option><option value="before">До еды</option><option value="during">С едой</option><option value="after">После еды</option></select><button type="submit" style={{ padding: 12, border: 0, borderRadius: 12, background: "linear-gradient(135deg,#748FFC,#5C7CFA)", color: "white", fontWeight: 700 }}>Сохранить препарат</button></form></details>
  </div>;
}
